// automatically generated by the FlatBuffers compiler, do not modify

package fbs

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Send struct {
	_tab flatbuffers.Table
}

func GetRootAsSend(buf []byte, offset flatbuffers.UOffsetT) *Send {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Send{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *Send) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Send) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Send) Data() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func SendStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func SendAddData(builder *flatbuffers.Builder, data flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(data), 0)
}
func SendEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
