// automatically generated by the FlatBuffers compiler, do not modify

package fbs

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Member struct {
	_tab flatbuffers.Table
}

func GetRootAsMember(buf []byte, offset flatbuffers.UOffsetT) *Member {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Member{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *Member) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Member) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Member) Type() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Member) Ref() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Member) MutateRef(n int64) bool {
	return rcv._tab.MutateInt64Slot(6, n)
}

func (rcv *Member) Role() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func MemberStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func MemberAddType(builder *flatbuffers.Builder, type_ flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(type_), 0)
}
func MemberAddRef(builder *flatbuffers.Builder, ref int64) {
	builder.PrependInt64Slot(1, ref, 0)
}
func MemberAddRole(builder *flatbuffers.Builder, role flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(role), 0)
}
func MemberEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
