// automatically generated by the FlatBuffers compiler, do not modify

package fbs

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Nd struct {
	_tab flatbuffers.Table
}

func GetRootAsNd(buf []byte, offset flatbuffers.UOffsetT) *Nd {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Nd{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *Nd) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Nd) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Nd) Ref() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Nd) MutateRef(n int64) bool {
	return rcv._tab.MutateInt64Slot(4, n)
}

func NdStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func NdAddRef(builder *flatbuffers.Builder, ref int64) {
	builder.PrependInt64Slot(0, ref, 0)
}
func NdEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
